# Generated by Django 2.1.1 on 2019-06-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredits',
            old_name='description',
            new_name='credits',
        ),
    ]
